FROM n8nio/n8n:latest

ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV N8N_PROTOCOL=https
ENV WEBHOOK_URL=${RENDER_EXTERNAL_URL}
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=${N8N_USER}
ENV N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}

EXPOSE 5678

ENTRYPOINT ["n8n", "start"]
